
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      
  - package-ecosystem: "github-actions"
    directory: "/.github/"
    schedule:
      interval: "daily"
      time: "00:00"
