version: '3.9'
services:
  resql:
    container_name: resql
    image: resql
    build:
      context: .
    environment:
      - sqlms.saved-queries-dir=/DSL
      - sqlms.datasources.[0].name=byk
      - sqlms.datasources.[0].jdbcUrl=jdbc:postgresql://database:5432/byk
      - sqlms.datasources.[0].username=byk
      - sqlms.datasources.[0].password=01234
      - logging.level.org.springframework.boot=INFO
      - server.port=8082
    volumes:
      - ./DSL:/DSL
    ports:
      - 8082:8082
    networks:
      - bykstack

  database:
    container_name: database
    image: postgres:14.1
    environment:
      - POSTGRES_USER=byk
      - POSTGRES_PASSWORD=01234
      - POSTGRES_DB=byk
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - bykstack

networks:
  bykstack:
    name: bykstack
    driver: bridge